Fix net-snmp netsnmptrapd.conf generation.
pfsense/FreeBSD-ports pull request #1060
Opened 2021-04-07 13:07 UTC by chrullrich

The snmptrapd configuration uses the keyword "snmpTrapdAddr" instead of
"agentaddress". This is probably a copy-paste bug.

Without this change, the "interface binding" option in the snmptrapd configuration page is ineffective:

    > head -n 1 /var/etc/netsnmptrapd.conf
    agentaddress udp:127.0.0.1:162
    > netstat -lanf inet | fgrep .162
    udp4       0      0 *.162                  *.*

, whereas:

    > head -n 1 /var/etc/netsnmptrapd.conf
    snmpTrapdAddr udp:127.0.0.1:162
    > netstat -lanf inet | fgrep .162
    udp4       0      0 127.0.0.1.162          *.*

2021-04-07 14:49 UTC, jim-p requested changes
As a part of this pull request, you must increase PORTVERSION or add a PORTREVISION line in the package Makefile. Without this version increase, the package will not be rebuilt to include the new change.

See https://docs.netgate.com/pfsense/en/latest/references/developer-style-guide.html#ports-packages-specific-rules

2021-04-07 14:49 UTC, jim-p commented
To effectively track changes and bug/feature requests, we require an entry on the [pfSense Redmine issue tracker](https://redmine.pfsense.org) associated with every pull request, and likewise the Redmine entry should also have a link back to the pull request.

Please associate this PR to a Redmine issue either by locating an existing issue at https://redmine.pfsense.org or by creating a new issue. Add a link to the Redmine issue that points to this PR, and also add a link on the PR to the Redmine issue.

For more information, see https://docs.netgate.com/pfsense/en/latest/development/pull-request.html
Thanks!

2021-04-07 15:01 UTC, chrullrich commented
I never include PORTREVISION bumps in ports patches because they may conflict with others. The person best placed to a) decide if the bump is required and b) do it, is the committer.

As for the pfSense bug, this is a one-line patch. Take it or leave it.

If it's easier for you, close the PR and fix the bug directly. You introduced it, after all.

    net-mgmt/pfSense-pkg-net-snmp]$ git blame -L 713,713 HEAD^ files/usr/local/pkg/net-snmp.inc
    95668eece9cea (jim-p 2017-01-15 17:10:29 -0500 713)             $snmptrapd_config .= "agentaddress " . implode(',', $agentaddresses) . "\n";

2021-06-23 15:07 UTC, rbgarga commented
Redmine ticket https://redmine.pfsense.org/issues/12073

2021-06-23 15:09 UTC, rbgarga commented
Manually merged.  Thanks!

2021-06-23 15:09 UTC, closed without merging