Added xmlrpc support to the sudo package
pfsense/FreeBSD-ports pull request #967
Opened 2020-10-22 15:32 UTC by infraweavers

Will only work on Pfsense > 2.4 however as this is adding a feature, we think it's reasonable to not have backwards compatibility here.

2020-10-23 19:07 UTC, rbgarga requested changes
All these comments are also valid for PR #968

2020-10-23 19:07 UTC, rbgarga commented on security/pfSense-pkg-sudo/files/usr/local/pkg/sudo.inc
> +if(!function_exists('pf_version')) {
This function can be removed

2020-10-23 19:07 UTC, rbgarga commented on security/pfSense-pkg-sudo/files/usr/local/pkg/sudo.inc
> +	if (pf_version() >= "2.4") {
No need to check if pfSense is >= 2.4 since the smallest supported version is 2.4.5-p1

2020-10-23 19:07 UTC, rbgarga commented on security/pfSense-pkg-sudo/files/usr/local/pkg/sudo.inc
> +		sudo_do_xmlrpc_sync($system_carp['synchronizetoip'], $varsyncport, $varsyncprotocol, $system_carp['username'], $system_carp['password'], 100);
Please break this really long line.  pfSense style says we should try to keep lines in ~80 columns.  Multiline statements must be indented with 4 spaces after previous line indentation.

2020-10-23 19:07 UTC, rbgarga commented on security/pfSense-pkg-sudo/files/usr/local/pkg/sudo.inc
> +	if (is_array($config['hasync'])) {
You can reverse this check and just return when it's false, then next block will be one level less indented

2020-10-26 10:49 UTC, infraweavers commented
@rbgarga all changed on this one

2020-10-26 15:03 UTC, rbgarga approved these changes

2020-10-27 17:09 UTC, jim-p requested changes

2020-10-27 17:09 UTC, jim-p commented on security/pfSense-pkg-sudo/files/usr/local/pkg/sudo.inc
> +	$resp = $rpc_client->xmlrpc_exec_php($execcmd2, $synctimeout);
Why are you using a function which executes PHP to execute a shell command which then runs PHP as a script?

Just execute the PHP directly without jumping through all the extra hoops.

2020-10-28 09:32 UTC, infraweavers commented
@jim-p changed, we basically copied snort's implementation hence the complexity

2020-10-28 14:14 UTC, jim-p commented
That makes sense, Snort is a lot more complex and may need to run that process in the background since it will take a lot longer. Not needed in these cases.

2020-10-28 14:15 UTC, jim-p approved these changes

2020-10-29 12:27 UTC, rbgarga commented
Manually merged in order to squash all commits into a single one.  Thanks!

2020-10-29 12:27 UTC, closed without merging