pfblockerng-devel: Add feeds from firebog.net. Implements #11022.
pfsense/FreeBSD-ports pull request #982
Opened 2020-10-31 01:32 UTC by Gosherm

Add additional blocker feeds listed at firebog.net.

https://redmine.pfsense.org/issues/11022

2020-11-05 13:59 UTC, rbgarga commented
@BBcan177 can you please take a look?

2020-12-01 15:09 UTC, Gosherm commented
@BBcan177, @rbgarga - This PR has been updated to be ready for merging with pfblockerng-devel 3

2020-12-01 15:47 UTC, rbgarga requested changes

2020-12-01 15:47 UTC, rbgarga commented on net/pfSense-pkg-pfBlockerNG-devel/Makefile
> +PORTVERSION=
You must set it to 3 instead of empty

2020-12-01 15:48 UTC, rbgarga commented
@BBcan177 can you review this one please?

2020-12-01 21:11 UTC, BBcan177 commented
@Gosherm 

For now, I would like to leave Malware Domain Lists in the Feeds.

Also can you remove the commit to the makefile, as I have some pending changes to make to the code, so I want to minimize the number of installation notifications that the users get.

Otherwise OK to merge.

Thanks!

2020-12-02 02:31 UTC, Gosherm commented on net/pfSense-pkg-pfBlockerNG-devel/Makefile
> +PORTVERSION=
Set back to 2 per request from BBCAN177

2020-12-02 02:48 UTC, Gosherm commented
Reverted makefile and malwarebytes changes per requests

2020-12-07 13:29 UTC, rbgarga commented
@BBcan177 please review

2020-12-07 16:25 UTC, BBcan177 commented
@Gosherm 

The **Info/Description** attributes should be more informative. 

Can you add the  "**info**" attribute to all of the feeds which are hosted on https://v.firebog.net/ which are formatted copies of the original source of those feeds, to indicate that to the users as info.

Otherwise its OK, but will get this merged once I submit the next version.

2020-12-15 11:29 UTC, rbgarga commented
@Gosherm when you address the change asked by @BBcan177 please rebase your fork and fix conflicts

2020-12-16 20:14 UTC, Gosherm commented
@rbgarga Rebased and unconflicted.

2020-12-16 20:15 UTC, Gosherm commented
@BBcan177 Changes made as requested

2020-12-21 05:35 UTC, BBcan177 commented
@Gosherm 
I just added a PR #1008 which is hopefully approved and merged tomorrow.

Unfortunately, the JSON for this PR is invalid. You need to add a "," to the line before each of the new "info:" lines that were recently added. I also suggest that once you make those changes, download the RAW file and test to make sure that the Feeds tab reads the file.

Thanks for your patience, but just need to do the last fixup.

2021-01-08 04:36 UTC, BBcan177 commented
Hi @Gosherm , would you be able to make these changes as I have another update coming soon. Thanks!

2021-02-04 05:26 UTC, BBcan177 commented
Hi @Gosherm, just checking to see if you are able to make those changes, or if its easier, I can add this to my next version? Thanks!

2021-02-05 10:39 UTC, rbgarga commented
Superseded by #1035

2021-02-05 10:39 UTC, closed without merging