Fix slow loading of HAProxy widget on dashboard, buy avoiding reapeated costly permissions checks.
pfsense/FreeBSD-ports pull request #994
Opened 2020-11-18 02:00 UTC by pruiz

In our current setup we have a few dozen frontends with a few backends under the hood. So for each server this is calling userHasPrivilage, which loads an parses config file every time.. adding ~2s to each loop iteration. This patch changes the code so privilegies are checked just once (before entering the foreach loop).

2020-11-18 19:49 UTC, jim-p requested changes
As a part of this pull request, you must increase PORTVERSION or add a PORTREVISION line in the package Makefile. Without this version increase, the package will not be rebuilt to include the new change.

See https://docs.netgate.com/pfsense/en/latest/references/developer-style-guide.html#ports-packages-specific-rules

2020-11-19 01:24 UTC, pruiz commented
@jim-p updated PORTVERSION as requested. ;)

2020-11-19 16:37 UTC, jim-p approved these changes

2020-12-01 15:51 UTC, rbgarga commented
Manually merged.  Thanks!

2020-12-01 15:51 UTC, closed without merging